name: Selenium Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: self-hosted
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      run: |
        sudo amazon-linux-extras enable python3.8
        sudo yum install -y python3.8
        python3.8 -m ensurepip --upgrade
        python3.8 -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Install Selenium and dependencies
      run: |
        pip3 install selenium
        curl -O https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo yum install -y google-chrome-stable

    - name: Run Selenium tests
      run: |
        python3.8 -m unittest discover -s tests -p "*.py"
      env:
        DOMAIN: https://mmacroscope.com

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: selenium-test-results
        path: reports/
